#
# Module manifest for module 'Ath.Omp'
#
# Generated by: Alex ter Horst
#
# Generated on: 2/21/2023
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule = '.\Ath.Omp.psm1'

    # Version number of this module.
    ModuleVersion = '0.0.1'

    GUID = '141286f1-c9a9-4645-b2d0-f29198fcf8c6'
    Author = 'Alex ter Horst'
    CompanyName = 'Unknown'
    Copyright = '(c) Alex ter Horst. All rights reserved.'
    Description = 'Oh My Posh helper functions'
    PowerShellVersion = '7.3.2'

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @('Set-PoshTheme')

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport   = @()

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport   = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{ } # End of PrivateData hashtable

}

